apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: istiocertmergers.medium.com
  labels:
    app.kubernetes.io/name: {{ include "istio-cert-merger.name" . }}
    helm.sh/chart: {{ include "istio-cert-merger.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  group: medium.com
  version: v1
  scope: Cluster
  names:
    plural: istiocertmergers
    singular: istiocertmerger
    kind: IstioCertMerger
    shortNames:
    - icms
    - icm
